import 'package:test/test.dart';
import 'package:poker_analyzer/core/training/generation/pack_yaml_config_parser.dart';
import 'package:poker_analyzer/core/training/generation/pack_generation_request.dart';
import 'package:poker_analyzer/models/game_type.dart';

void main() {
  test('parse returns requests', () {
    const yaml = '''
packs:
  - gameType: tournament
    bb: 10
    positions: [sb, bb]
    title: Test
    description: Desc
    tags: [pushfold]
    count: 20
  - gameType: cash
    bb: 50
    positions: [btn]
    title: Cash
    description: Example
    tags: [cash]
''';
    final parser = PackYamlConfigParser();
    final list = parser.parse(yaml);
    expect(list.length, 2);
    expect(list.first.gameType, GameType.tournament);
    expect(list.first.bb, 10);
    expect(list.first.positions, ['sb', 'bb']);
    expect(list.first.title, 'Test');
    expect(list.first.tags, ['pushfold']);
    expect(list.first.count, 20);
    expect(list.first.multiplePositions, false);
    expect(list.last.count, 25);
    expect(list.last.gameType, GameType.cash);
  });

  test('parse applies default tags', () {
    const yaml = '''
defaultTags: [pushfold, autogenerated]
packs:
  - gameType: tournament
    bb: 10
    positions: [sb]
  - gameType: cash
    bb: 5
    positions: [bb]
    tags: [cash]
''';
    final parser = PackYamlConfigParser();
    final list = parser.parse(yaml);
    expect(list.first.tags, ['pushfold', 'autogenerated']);
    expect(list.last.tags, ['cash']);
  });

  test('parse reads multiplePositions flag', () {
    const yaml = '''
packs:
  - gameType: tournament
    bb: 15
    positions: [btn, sb]
    multiplePositions: true
''';
    final parser = PackYamlConfigParser();
    final list = parser.parse(yaml);
    expect(list.first.multiplePositions, true);
  });
}
