include: package:lints/recommended.yaml

linter:
  rules:
    unnecessary_import: true
    unused_field: true
    avoid_print: true
    prefer_final_locals: true
    always_declare_return_types: true
    public_member_api_docs: false
