
analyzer:
  exclude:
    - lib/services/**
    - lib/plugins/**
    - lib/utils/shared_prefs_keys.dart
    - lib/models/saved_hand.dart
    - lib/models/training_pack_template_model.dart
    - lib/models/street_investments.dart
    - lib/services/**
    - test/services/**

