# Poker Analyzer analysis options
analyzer:
  exclude:
    - lib/screens/**
    - lib/widgets/**
    - lib/ui/**
    - lib/plugins/**
    - lib/providers/**
    - lib/models/v2/**
    - test/**
    - tool/**
  language:
    strict-inference: false
    strict-raw-types: false

linter:
  rules:
    - avoid_print
    - prefer_final_locals
    - unawaited_futures
