# Poker Analyzer analysis options
analyzer:
  exclude:
    - lib/services/**
    - lib/shop/**
    - lib/plugins/**
  language:
    strict-inference: false
    strict-raw-types: false

linter:
  rules:
    - avoid_print
    - prefer_final_locals
    - unawaited_futures
