name: poker_analyzer
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  http: ^1.1.0
  collection: ^1.18.0
  uuid: ^4.2.1
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  lottie: ^3.3.1
  animations: ^2.0.8
  package_info_plus: ^8.0.0
  yaml: ^3.1.2
  logging: ^1.2.0
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.1
  drift: ^2.17.0
  drift_flutter: ^2.17.0
  sqlite3_flutter_libs: ^0.5.16
  path: ^1.9.0
  archive: ^3.4.10
  share_plus: ^10.0.0
  file_picker: ^8.0.0+1
  csv: ^6.0.0
  pdf: ^3.11.1
  printing: ^5.12.0
  flutter_markdown: ^0.7.1
  url_launcher: ^6.2.5
  intl_utils: ^2.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  json_serializable: ^6.8.0
  freezed: ^2.4.6
  drift_dev: ^2.17.0

flutter:
  generate: true            # <— включаем генерацию локализаций
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/theory/
