name: poker_analyzer
description: A new Flutter project.

publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

executables:
  batch_generate: bin/batch_generate.dart

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.0
  path_provider: ^2.0.15
  path: ^1.8.3
  open_filex: ^4.7.0
  file_picker: ^6.2.1
  desktop_drop: ^0.6.0
  fl_chart: ^0.66.0
  pie_chart: ^5.4.0
  pdf: ^3.10.4
  printing: ^5.12.0
  provider: ^6.0.5
  flutter_colorpicker: ^1.0.3
  intl: ^0.20.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  flutter_localizations:
    sdk: flutter
  sticky_headers: ^0.3.0+2
  archive: ^4.0.0
  share_plus: ^7.0.0
  uuid: ^4.0.0
  synchronized: ^3.0.0
  csv: ^6.0.0
  timeago: ^3.6.0
  file_saver: ^0.2.14
  permission_handler: ^11.3.0
  confetti: ^0.7.0
  poker_solver: ^1.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  webview_flutter: ^4.2.2
  markdown: ^7.1.1
  table_calendar: ^3.0.9
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  image: ^4.1.3
  firebase_core: ^3.0.0
  cloud_firestore: ^4.8.0
  firebase_auth: ^4.8.0
  firebase_storage: ^11.2.0
  google_sign_in: ^6.1.5
  connectivity_plus: ^6.0.4
  url_launcher: ^6.1.11

dependency_overrides:
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.25.0

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  yaml: ^3.1.1
  crypto: ^3.0.2
  pedantic: ^1.11.1
  fake_cloud_firestore: ^3.1.0
  firebase_auth_mocks: ^0.14.0

flutter:

  generate: true

  uses-material-design: true

  assets:
    - assets/cards/card_back.png
    - assets/spots/spots.json
    - assets/training_packs/
    - assets/training_templates/
    - assets/templates/initial/
    - assets/ranges/
    - assets/packs/

# Release build configuration for the demo entry point. Run
# `flutter build apk --target=main.dart` to compile the demo
# application with these settings.
flutter_build:
  targets:
    demo: main.dart
