id: 3bet_push_btn_vs_lj
title: 3bet Push BTN vs LJ
description: BTN 3bet shoves vs LJ opens at 25bb
stages:
  - id: 3bet_push_btn_vs_lj_stage
    title: 3bet Push
    description: BTN shoves over LJ open
    packId: 3bet_push_btn_vs_lj
    requiredAccuracy: 80
    minHands: 10
