id: sample
title: Sample Learning Path
description: Sample learning path for tests.
tags:
  - sample
  - test
stages:
  - id: s1
    title: Stage One
    description: First stage
    packId: pack1
    requiredAccuracy: 80
    minHands: 10
    unlocks:
      - s2
  - id: s2
    title: Stage Two
    description: Second stage
    packId: pack2
    requiredAccuracy: 70
    minHands: 5
