packs:
  - gameType: tournament
    bb: 10
    positions: [sb, bb]
    title: Example Pack
    description: Example tournament pack
    tags: [pushfold]
    count: 10
  - gameType: cash
    bb: 50
    positions: [btn]
    title: Cash Pack
    description: Example cash pack
    tags: [cash]
    count: 10
