enum SpotKind {
  l2_open_fold,
  l2_threebet_push,
  l2_limped,
  l4_icm,
  callVsJam,
  l3_postflop_jam,
  l3_checkraise_jam,
  l3_check_jam_vs_cbet,
  l3_donk_jam,
  l3_overbet_jam,
  l3_raise_jam_vs_donk,
  l3_bet_jam_vs_raise,
  l3_raise_jam_vs_cbet,
  l3_probe_jam_vs_raise,
  l3_river_jam_vs_bet,
  l3_turn_jam_vs_bet,
  l3_flop_jam_vs_bet,
  l3_flop_jam_vs_raise,
  l3_turn_jam_vs_raise,
  l3_river_jam_vs_raise,
  l4_icm_bubble_jam_vs_fold,
  l4_icm_ladder_jam_vs_fold,
  l4_icm_sb_jam_vs_fold,
  l4_icm_bb_jam_vs_fold,
  l1_core_call_vs_price,
}

const Set<String> kSpotKindUniverse = {
  'l2_open_fold',
  'l2_threebet_push',
  'l2_limped',
  'l4_icm',
  'callVsJam',
  'l3_postflop_jam',
  'l3_checkraise_jam',
  'l3_check_jam_vs_cbet',
  'l3_donk_jam',
  'l3_overbet_jam',
  'l3_raise_jam_vs_donk',
  'l3_bet_jam_vs_raise',
  'l3_raise_jam_vs_cbet',
  'l3_probe_jam_vs_raise',
  'l3_river_jam_vs_bet',
  'l3_turn_jam_vs_bet',
  'l3_flop_jam_vs_bet',
  'l3_flop_jam_vs_raise',
  'l3_turn_jam_vs_raise',
  'l3_river_jam_vs_raise',
  'l4_icm_bubble_jam_vs_fold',
  'l4_icm_ladder_jam_vs_fold',
  'l4_icm_sb_jam_vs_fold',
  'l4_icm_bb_jam_vs_fold',
  'l1_core_call_vs_price',
};

bool isValidSpotKind(String s) => kSpotKindUniverse.contains(s);

