name: ASCII Auto-Fix

on:
  pull_request_target:
    types: [opened, synchronize, reopened, labeled]

permissions:
  contents: write
  pull-requests: write

jobs:
  autofix:
    if: |
      contains(github.event.pull_request.labels.*.name, 'auto-fix') &&
      github.event.pull_request.head.repo.fork == false
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          persist-credentials: true
          fetch-depth: 0

      - name: Run ASCII fixer
        shell: bash
        run: |
          set -euo pipefail
          bash tool/dev/ascii_fix_all.sh
          if git diff --quiet; then
            echo "No ASCII fixes needed."
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "chore(ci): auto-fix smart punctuation to ASCII"
          git push
