name: autoformat-fix

on:
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  autoformat-fix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Get deps
        run: flutter pub get

      - name: Format (write changes)
        run: dart format .

      - name: Auto-commit formatting
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ci: autoformat"
          skip_dirty_check: false
        continue-on-error: true
