name: pr-autoformat (push-fix)

on:
  pull_request:
    branches: [ main ]
    types: [opened, reopened, synchronize]

permissions:
  contents: write

jobs:
  autoformat:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          ref: ${{ github.head_ref }}

      - name: Setup Flutter (stable)
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Pub get
        run: flutter pub get

      - name: Format and push
        run: |
          dart format --set-exit-if-changed . || true
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A && git commit -m "ci(autoformat): apply dart format" || true
          git push
