name: CI — Fast PR Checks

on:
  pull_request:
    branches: [main, develop, feature/**]
    paths-ignore:
      - '**/docs/**'
      - '**.md'

jobs:
  fast-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 12

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter (3.27.x)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.0'   # фиксируем на версии с Dart >= 3.6
          cache: true

      - name: Show Flutter & Dart versions
        run: |
          flutter --version
          dart --version

      - name: Install dependencies
        run: flutter pub get

      - name: Flutter analyze
        run: flutter analyze

      - name: Run minimal tests with coverage
        run: flutter test --no-pub --coverage
