name: L2 Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  l2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: pub-cache
      - run: dart pub get
      - run: dart test test/l2_*
