name: L2 Tests (conditional)

on:
  pull_request:
  push:
    branches: [ main ]

concurrency:
  group: l2-tests-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  l2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Запускаем тесты только если есть релевантные изменения
      - name: Detect relevant changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            l2:
              - 'assets/packs/l2/**'
              - 'assets/theory/**'
              - 'tool/validators/**'
              - 'tool/metrics/**'
              - 'tool/autogen/**'
              - 'test/l2_*.dart'
              - 'pubspec.*'

      - name: Skip (no relevant L2 changes)
        if: steps.filter.outputs.l2 != 'true'
        run: echo "No relevant L2 changes — skipping." && exit 0

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - run: dart --version

      - name: Cache pub
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: pub-${{ runner.os }}-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            pub-${{ runner.os }}-

      - run: flutter pub get
      - name: Check L2 theory snippet coverage
        run: dart run tool/validators/theory_snippet_coverage.dart --packs assets/packs/l2 --snippets assets/theory/l2/snippets.yaml --min 0.90
      - name: Generate L2 packs (seed 111)
        run: dart run tool/autogen/l2_pack_generator.dart --preset all --seed 111 --out build/tmp/l2/111
      - name: Generate L2 packs (seed 222)
        run: dart run tool/autogen/l2_pack_generator.dart --preset all --seed 222 --out build/tmp/l2/222
      - name: Generate L2 packs (seed 333)
        run: dart run tool/autogen/l2_pack_generator.dart --preset all --seed 333 --out build/tmp/l2/333
      - name: Validate presets
        run: dart run tool/validators/preset_validator.dart --dir build/tmp/l2
      - name: Run L2 tests
        run: dart test test/l2_*
      - run: dart run tool/metrics/l2_metrics_report.dart --packs assets/packs/l2 --snippets assets/theory/l2/snippets.yaml --out build/reports/l2_report.md
      - run: |
          echo "::group::L2 Metrics"
          cat build/reports/l2_report.md
          echo "::endgroup::"
      - uses: actions/upload-artifact@v4
        with:
          name: l2_report.md
          path: build/reports/l2_report.md
