name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'
          channel: stable
      - name: Repair pub cache
        run: flutter pub cache repair
      - name: Install dependencies
        run: flutter pub get
      - name: Verify pubspec.lock
        run: dart pub get --dry-run
      - name: Run tests
        run: flutter test --run-skipped
