name: Content Fast Lane

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'content/**'
      - 'tool/fast_content_check.dart'
      - 'lib/content/jsonl_validator.dart'
  push:
    branches:
      - 'feature/**'
      - 'feat/**'
    paths:
      - 'content/**'
      - 'tool/fast_content_check.dart'
      - 'lib/content/jsonl_validator.dart'

jobs:
  fast-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - name: Pub get
        run: dart pub get
      - name: Run fast content check
        run: dart run tool/fast_content_check.dart

