name: L10n Drift

on:
  pull_request:
    branches: [ main ]
    paths:
      - "lib/l10n/**"
      - ".github/workflows/l10n-drift.yml"

jobs:
  l10n-drift:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 50 }
      - name: Detect drift in lib/l10n/**
        shell: bash
        run: |
          BASE="origin/${GITHUB_BASE_REF:-main}"
          git fetch --no-tags --depth=50 origin main >/dev/null 2>&1 || true
          CHANGED=$(git diff --name-only "$BASE"...HEAD | grep '^lib/l10n/' || true)
          if [ -n "$CHANGED" ]; then
            echo "::error title=L10n drift detected::Changes under lib/l10n/** must be reverted or regenerated (no manual edits)."
            echo "$CHANGED"
            exit 1
          fi
          echo "OK: no l10n drift."
