name: Precommit Mirror

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - "lib/live/**"
      - "test/live_**"
      - "lib/telemetry/telemetry.dart"
      - "tool/fast_live_check.dart"
      - "content/**"
      - "tool/fast_content_check.dart"
      - "lib/content/jsonl_validator.dart"
      - "tool/precommit.dart"
      - ".github/workflows/precommit.yml"
  push:
    branches: [ "feature/**", "feat/**" ]
    paths:
      - "lib/live/**"
      - "test/live_**"
      - "lib/telemetry/telemetry.dart"
      - "tool/fast_live_check.dart"
      - "content/**"
      - "tool/fast_content_check.dart"
      - "lib/content/jsonl_validator.dart"
      - "tool/precommit.dart"

jobs:
  precommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: "stable"
      - name: Dart version
        run: dart --version
      - name: Pub get
        run: dart pub get
      - name: Run precommit
        run: dart run tool/precommit.dart

