name: Codex Presubmit (format+analyze)

on:
  pull_request: {}   # важно: брать все PR; фильтруем по head-ветке ниже

permissions:
  contents: write    # для авто-коммита форматирования

concurrency:
  group: presubmit-${{ github.event.pull_request.head.sha || github.sha }}
  cancel-in-progress: true

jobs:
  presubmit:
    # Только для PR, где head-ветка начинается с "codex/"
    if: ${{ startsWith(github.head_ref, 'codex/') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Flutter (Dart toolchain)
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.27.0'
          cache: true

      - name: Autoformat Dart
        id: fmt
        run: |
          dart format -o write tool lib test || true
          if git diff --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit format (if needed)
        if: steps.fmt.outputs.changed == 'true'
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "style: dart format (autofix)"
          git push

      # Узкий анализ только по pure-Dart зонам (не трогаем UI/Flutter)
      - name: Dart analyze (limited scope)
        run: |
          # анализируем только эти директории/файлы
          dart analyze \
            tool \
            lib/services \
            lib/l3 \
            test/l3_* \
            test/l2_* \
            --no-fatal-warnings --no-fatal-infos || true
