name: Codex Presubmit (format+analyze)

on:
  pull_request:
  push:
    branches:
      - '**'

concurrency:
  group: presubmit-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  presubmit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Flutter (Dart toolchain)
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.27.0'
          cache: true

      - name: Autoformat Dart (workspace)
        run: dart format -o write $(git ls-files '*.dart')

      # ВАЖНО: коммитим автоформат ТОЛЬКО на push в ветку, не на pull_request
      - name: Commit format (if needed)
        if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/heads/') }}
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if ! git diff --quiet; then
            git add -A
            git commit -m "style: dart format (autofix)"
            git push
          fi

      # Анализ оставляем нефатальным, чтобы не блокировать PR
      - name: Dart analyze (non-fatal)
        run: dart analyze || true
