name: sanity-informational

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  sanity:
    runs-on: ubuntu-latest
    continue-on-error: true   # ← только здесь, не дублируем в шагах

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Get deps
        run: flutter pub get

      # любые быстрые sanity-проверки оставляй тут
      - name: Smoke build (web)
        run: flutter build web --release --no-tree-shake-icons
