name: Codex Sanity (analyze only)

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read

concurrency:
  group: codex-sanity-${{ github.event.pull_request.head.sha || github.sha }}
  cancel-in-progress: true

jobs:
  sanity:
    if: ${{ startsWith(github.event.pull_request.head.ref, 'codex/') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR head
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          fetch-depth: 0

      - name: Setup Flutter (stable)
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Pub get
        run: |
          if [ -f pubspec.yaml ]; then flutter pub get; fi

      - name: Analyze (informational)
        run: flutter analyze
        continue-on-error: true
