name: Tests (on label or main)
on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]
  push:
    branches: [ main ]
jobs:
  tests:
    if: github.event_name == 'push' ||
        contains(join(fromJson(toJson(github.event.pull_request.labels)).*.name, ' '), 'run-tests')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with: { channel: stable, flutter-version: '3.27.0', cache: true }
      - run: flutter pub get
      - name: Format check (repo-wide but no write)
        run: dart format --output=none --set-exit-if-changed .
      - name: Analyze (repo-wide, fatal)
        run: flutter analyze
      - name: Unit tests (repo-wide)
        run: dart test -r expanded
