name: Theory Integrity

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    # Триггерим только когда меняются файлы теории
    paths:
      - 'assets/**/*.yml'
      - 'assets/**/*.yaml'
      - 'assets/**/theory/**'
      - 'theory/**'
      - 'yaml_out/**'
  workflow_dispatch:

concurrency:
  group: theory-integrity-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  verify:
    name: verify
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect theory changes
        id: detect
        run: |
          set -euo pipefail
          CHANGED="$(git diff --name-only origin/${{ github.base_ref }}...HEAD | grep -E '^(assets/.*\.ya?ml|assets/.*/theory/|theory/|yaml_out/)')"
          if [ -n "$CHANGED" ]; then
            echo "has_changes=true" >> "$GITHUB_OUTPUT"
            echo "Theory changes detected:"
            echo "$CHANGED"
          else
            echo "has_changes=false" >> "$GITHUB_OUTPUT"
            echo "No theory changes -> skip"
          fi

      - name: Set up Flutter
        if: steps.detect.outputs.has_changes == 'true'
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install dependencies
        if: steps.detect.outputs.has_changes == 'true'
        run: flutter pub get

      - name: Strict verify
        if: steps.detect.outputs.has_changes == 'true'
        env:
          MODE: strict
        run: |
          echo "mode=$MODE"
          tool/theory_verify.sh --mode "$MODE"
