name: Theory Manifest – Generate baseline

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  generate-baseline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
        with:
          fetch-depth: 0

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8'
          channel: 'stable'

      - name: Disable Flutter analytics
        run: flutter config --no-analytics

      - name: Install dependencies
        run: flutter pub get

      - name: Build dir list from repo (*.yaml)
        id: dirs
        shell: bash
        run: |
          set -euo pipefail
          DIRS="$(git ls-files '*.yaml' | xargs -r dirname | sort -u || true)"
          if [ -z "${DIRS}" ]; then
            echo "no_yaml=1" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          ARGS=""
          for d in $DIRS; do
            ARGS="$ARGS --dir $d"
          done
          echo "no_yaml=0" >> "$GITHUB_OUTPUT"
          echo "args=${ARGS}" >> "$GITHUB_OUTPUT"

      - name: Generate/Update manifest (standalone, no lib compile)
        if: steps.dirs.outputs.no_yaml == '0'
        id: gen
        shell: bash
        run: |
          set -euo pipefail
          ARGS="${{ steps.dirs.outputs.args }}"
          dart run tool/theory_manifest_cli.dart ${ARGS} --out theory_manifest.json
          if git diff --quiet -- theory_manifest.json; then
            echo "changed=0" >> "$GITHUB_OUTPUT"
          else
            echo "changed=1" >> "$GITHUB_OUTPUT"
          fi

      # На всякий пожарный убираем побочные изменения Flutter из воркспейса (не критично, но полезно)
      - name: Drop unrelated generated changes
        if: steps.gen.outputs.changed == '1'
        shell: bash
        run: |
          git restore --worktree --staged lib/l10n || true
          git restore --worktree --staged macos/Flutter/GeneratedPluginRegistrant.swift || true

      - name: Create PR with baseline
        if: steps.gen.outputs.changed == '1'
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: add baseline theory manifest"
          title: "chore: add baseline theory manifest"
          body: |
            Generated/updated theory_manifest.json across all YAML directories found in the repo using a standalone generator.
            Unblocks strict verification in the Theory Integrity CI without compiling the Flutter app.
          branch: manifest/baseline
          signoff: false
          add-paths: |
            theory_manifest.json
