name: Theory Manifest – Generate baseline

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Generate theory manifest
        run: dart run bin/poker_analyzer.dart manifest generate ${ARGS} --out theory_manifest.json

      - name: Update theory manifest
        run: dart run bin/poker_analyzer.dart manifest update ${ARGS}

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add theory_manifest.json
          git commit -m "Update theory manifest [CI]" || echo "No changes to commit"
          git push
