name: "Theory Manifest - Generate baseline"

on:
  workflow_dispatch:

permissions:
  contents: write

env:
  THEORY_DIRS: assets

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Generate/Update manifest
        id: gen
        shell: bash
        run: |
          set -euo pipefail
          IFS=',' read -ra DIRS <<< "${THEORY_DIRS:-assets}"
          first=1
          for d in "${DIRS[@]}"; do
            [ -d "$d" ] || continue
            echo "Processing dir: $d"
            if [ "$first" -eq 1 ]; then
              dart run bin/poker_analyzer.dart manifest generate --dir "$d" --out theory_manifest.json
              first=0
            else
              dart run bin/poker_analyzer.dart manifest update --dir "$d"
            fi
          done
          if [ "$first" -eq 1 ]; then
            echo "No theory dirs present; nothing to generate"
            echo "changed=0" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          # отметим, есть ли реальный diff по файлу
          if git diff --quiet -- theory_manifest.json; then
            echo "changed=0" >> "$GITHUB_OUTPUT"
          else
            echo "changed=1" >> "$GITHUB_OUTPUT"
          fi

      - name: Create PR with baseline
        if: steps.gen.outputs.changed == '1'
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: add baseline theory manifest"
          title: "chore: add baseline theory manifest"
          body: |
            Generated/updated theory_manifest.json to enable strict CI verification.
            This PR was created by the one-shot workflow.
          branch: manifest/baseline
          signoff: false
