name: Theory Integrity

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - 'assets/**/*.yml'
      - 'assets/**/*.yaml'
      - 'assets/**/theory/**'
      - 'theory/**'
      - 'yaml_out/**'
  workflow_dispatch:

concurrency:
  group: theory-integrity-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  theory-integrity:
    name: Theory Integrity (strict on theory changes)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Flutter version
        run: flutter --version

      - name: Pub deps cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Install deps
        run: flutter pub get

      - name: Run Theory Integrity (strict)
        env:
          MODE: strict
        run: |
          echo "mode=$MODE"
          dart run bin/ci_report.dart --mode $MODE
