name: Theory Manifest – Generate baseline

on:
  workflow_dispatch:

jobs:
  generate-baseline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0' # фикс под Dart >=3.6.0

      - name: Install dependencies
        run: flutter pub get

      - name: Generate manifest
        run: dart run bin/poker_analyzer.dart manifest generate ${ARGS} --out theory_manifest.json

      - name: Update manifest
        run: dart run bin/poker_analyzer.dart manifest update ${ARGS}

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add theory_manifest.json
          git commit -m "Update theory_manifest.json [skip ci]" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
