name: Theory Manifest – Generate baseline
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate baseline manifest (Python, no Flutter)
        id: gen
        shell: bash
        run: |
          set -euo pipefail
          python3 - <<'PY'
          import os, json, hashlib
          ROOTS = ["assets"]  # где лежат YAML
          exts = {".yaml", ".yml"}
          files = []
          for root in ROOTS:
              if not os.path.isdir(root):
                  continue
              for r, _, fns in os.walk(root):
                  for fn in fns:
                      if os.path.splitext(fn)[1].lower() in exts:
                          files.append(os.path.join(r, fn))
          files.sort()
          mani = {"version": 1, "strict": False, "files": {}}
          for p in files:
              with open(p, "rb") as fh:
                  sha = hashlib.sha256(fh.read()).hexdigest()
              mani["files"][p] = {"sha256": sha}
          with open("theory_manifest.json", "w", encoding="utf-8") as out:
              json.dump(mani, out, ensure_ascii=False, indent=2)
          print(f"Wrote theory_manifest.json with {len(files)} files")
          PY
          echo "changed=1" >> "$GITHUB_OUTPUT"

      - name: Create PR with baseline
        if: steps.gen.outputs.changed == '1'
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: add baseline theory manifest"
          title: "chore: add baseline theory manifest"
          body: |
            Generated theory_manifest.json (soft mode, strict=false).
            Flip `"strict": true` later to enable strict CI.
          branch: manifest/baseline
          signoff: false
