name: Theory Manifest: Generate baseline

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - run: flutter pub get

      - id: dirs
        shell: bash
        run: |
          set -euo pipefail
          DIRS="$(git ls-files '*.yaml' | xargs -r dirname | sort -u || true)"
          if [ -z "${DIRS}" ]; then
            echo "no_yaml=1" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          ARGS=""
          for d in $DIRS; do ARGS="$ARGS --dir $d"; done
          echo "no_yaml=0" >> "$GITHUB_OUTPUT"
          echo "args=${ARGS}" >> "$GITHUB_OUTPUT"

      - id: gen
        if: steps.dirs.outputs.no_yaml == '0'
        shell: bash
        run: |
          set -euo pipefail
          ARGS="${{ steps.dirs.outputs.args }}"
          dart run bin/poker_analyzer.dart manifest generate ${ARGS} --out theory_manifest.json
          dart run bin/poker_analyzer.dart manifest update ${ARGS}
          if git diff --quiet -- theory_manifest.json; then
            echo "changed=0" >> "$GITHUB_OUTPUT"
          else
            echo "changed=1" >> "$GITHUB_OUTPUT"
          fi

      - uses: peter-evans/create-pull-request@v6
        if: steps.gen.outputs.changed == '1'
        with:
          commit-message: "chore: add baseline theory manifest"
          title: "chore: add baseline theory manifest"
          body: |
            Generated/updated theory_manifest.json across all YAML directories found in the repo.
            Enables strict verification in Theory Integrity CI.
          branch: manifest/baseline
          signoff: false
