name: Theory Integrity

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: theory-integrity-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  verify:
    name: verify
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect theory changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: |
            theory:
              - 'theory/**'
              - 'content/theory/**'
              - 'theory_index.json'
              - 'training_packs/**.yaml'
              - 'packs/**.yaml'

      - name: Set up Flutter
        if: steps.filter.outputs.theory == 'true'
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install dependencies
        if: steps.filter.outputs.theory == 'true'
        run: flutter pub get

      - name: Strict verify
        if: steps.filter.outputs.theory == 'true'
        env:
          MODE: strict
        run: |
          echo "mode=$MODE"
          bash tool/theory_verify.sh

