name: Theory Manifest – Generate baseline

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

defaults:
  run:
    shell: bash

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Build dir list from repo (*.yaml)
        id: dirs
        run: |
          set -euo pipefail
          DIRS="$(git ls-files '*.yaml' | xargs -r dirname | sort -u || true)"
          if [ -z "${DIRS}" ]; then
            echo "no_yaml=1" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          ARGS=""
          for d in $DIRS; do
            ARGS="$ARGS --dir $d"
          done
          echo "no_yaml=0" >> "$GITHUB_OUTPUT"
          echo "args=${ARGS}" >> "$GITHUB_OUTPUT"

      - name: Generate/Update manifest
        if: steps.dirs.outputs.no_yaml == '0'
        id: gen
        run: |
          set -euo pipefail
          ARGS="${{ steps.dirs.outputs.args }}"
          # Use standalone CLI to avoid compiling the Flutter app
          dart run tool/theory_manifest_cli.dart ${ARGS} --out theory_manifest.json
          if git diff --quiet -- theory_manifest.json; then
            echo "changed=0" >> "$GITHUB_OUTPUT"
          else
            echo "changed=1" >> "$GITHUB_OUTPUT"
          fi

      - name: Create PR with baseline
        if: steps.gen.outputs.changed == '1'
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: add baseline theory manifest"
          title: "chore: add baseline theory manifest"
          body: |
            Generated/updated theory_manifest.json across all YAML directories found in the repo.
            Enables strict verification in Theory Integrity CI.
          branch: manifest/baseline
          signoff: false
