name: Theory Integrity

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

env:
  THEORY_DIRS: assets,yaml_out,theory

jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Collect YAML files
        id: yml
        shell: bash
        run: |
          set -euo pipefail
          IFS=',' read -ra DIRS <<< "${THEORY_DIRS}"
          FILES=()
          for d in "${DIRS[@]}"; do
            [[ -d "$d" ]] || continue
            while IFS= read -r -d '' f; do FILES+=("$f"); done < <(find "$d" -type f \( -name '*.yml' -o -name '*.yaml' \) -print0)
          done
          if [[ ${#FILES[@]} -eq 0 ]]; then
            echo "has_yaml=0" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          printf '%s\n' "${FILES[@]}" > yaml_files.txt
          echo "has_yaml=1" >> "$GITHUB_OUTPUT"

      - name: Soft verify (no fail on missing report)
        if: steps.yml.outputs.has_yaml == '1'
        shell: bash
        run: |
          set -euo pipefail
          # Если отчёт ещё не генерится пайплайном — soft-режим не фейлит job.
          dart run bin/ci_report.dart --mode=soft --markdown | tee theory_summary.md
          # Код выхода soft-режима всегда 0. Если позже перейдём на strict — поднимем порог.

      - name: Upload summary artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: theory-summary
          path: theory_summary.md
          if-no-files-found: warn
