name: Theory Manifest – Generate baseline

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Generate/Update manifest
        id: gen
        shell: bash
        run: |
          set -euo pipefail
          CHANGED=0

          if [ -d assets ]; then
            echo "Generating manifest for ./assets"
            dart run bin/poker_analyzer.dart manifest generate --dir assets --out theory_manifest.json
            CHANGED=1
          fi

          if [ "$CHANGED" = "0" ]; then
            echo "No assets dir present; nothing to generate"
            echo "changed=0" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          echo "changed=1" >> "$GITHUB_OUTPUT"

      - name: Create PR with baseline
        if: steps.gen.outputs.changed == '1'
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: add baseline theory manifest"
          title: "chore: add baseline theory manifest"
          body: |
            Generated/updated theory_manifest.json to enable strict CI verification.
            This PR was created by the one-shot workflow.
          branch: manifest/baseline
          signoff: false
