name: Theory Manifest – Generate baseline

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  generate-baseline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: "3.9.0"
      - run: dart --version
      - run: dart pub get
      - run: dart run tooling/theory_manifest.dart --mode=baseline
