name: Unit Tests (Nightly Full)

on:
  schedule:
    - cron: '0 2 * * *'  # 02:00 UTC ежедневно

concurrency:
  group: unit-tests-nightly
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  full-run:
    name: Nightly Full Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
        with:
          fetch-depth: 0
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - run: flutter --version
      - uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-
      - run: bash scripts/setup_flutter_localprops.sh
      - run: flutter pub get
      - run: flutter test --coverage --concurrency=6
