name: Unit Tests (PR & Push)

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - '**/*.md'

concurrency:
  group: unit-tests-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Flutter version
        run: flutter --version

      - name: Cache Pub dependencies
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Bootstrap Flutter local.properties
        run: bash scripts/setup_flutter_localprops.sh

      - name: Install dependencies
        run: flutter pub get

      # --- Tests toggle ---
      # На push в main тесты всегда запускаются.
      # В PR по умолчанию тесты пропускаем; чтобы включить — добавь лейбл 'run-tests'.
      - name: Run tests (push & labeled PRs)
        if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'run-tests')) }}
        run: |
          set -Eeuo pipefail
          FILES=("test/ci_canary_test.dart")
          # если есть быстрые smoke-тесты — добавим их
          [ -d test/smoke ] && FILES+=("test/smoke")
          flutter test --exclude-tags=slow -r expanded --concurrency=6 "${FILES[@]}"

      - name: Skip tests (default for PRs without label)
        if: ${{ github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, 'run-tests') }}
        run: echo "PR tests are skipped. Add label 'run-tests' to enable."
