name: Unit Tests (Nightly Full)

on:
  schedule:
    - cron: '0 2 * * *'  # 02:00 UTC ежедневно

concurrency:
  group: unit-tests-nightly
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  full-run:
    name: Nightly Full Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Flutter (3.27.x)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.0'
          cache: true

      - name: Show Flutter & Dart versions
        run: |
          flutter --version
          dart --version

      - name: Cache Pub dependencies
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Bootstrap Flutter local.properties
        run: bash scripts/setup_flutter_localprops.sh

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test --coverage --concurrency=6
