name: Unit tests

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
  workflow_dispatch:

jobs:
  unit:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      # Берём только быстрые headless-наборы для CI-мерджа
      - name: Detect fast test dirs
        id: dirs
        shell: bash
        run: |
          set -euo pipefail
          DIRS=()
          [[ -d test/tools ]] && DIRS+=("test/tools")
          [[ -d test/headless ]] && DIRS+=("test/headless")
          if [[ ${#DIRS[@]} -eq 0 ]]; then
            echo "has_tests=0" >> "$GITHUB_OUTPUT"
          else
            printf '%s ' "${DIRS[@]}" > dirs.txt
            echo "has_tests=1" >> "$GITHUB_OUTPUT"
            echo "list=$(cat dirs.txt)" >> "$GITHUB_OUTPUT"
          fi

      - name: Run tests (Flutter, compact, serialized)
        if: steps.dirs.outputs.has_tests == '1'
        shell: bash
        run: |
          # Компактный вывод и последовательный прогон для стабильности
          flutter test -r compact -j 1 ${{ steps.dirs.outputs.list }}

      - name: No tests found
        if: steps.dirs.outputs.has_tests != '1'
        run: echo "No fast test directories found. Skipping."
