name: Unit tests

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
  workflow_dispatch:

jobs:
  unit:
    runs-on: ubuntu-latest
    timeout-minutes: 8

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter (for tooling + pub)
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Versions
        run: |
          flutter --version
          dart --version

      - name: Install dependencies
        run: flutter pub get

      # Белый список только 2-х стабильных тестов (исключаем plugin_scaffold & batch_generate)
      - name: Build whitelist of tests
        id: files
        shell: bash
        run: |
          set -euo pipefail
          WHITELIST=()
          [[ -f "test/tools/schema_check_unit_test.dart" ]] && WHITELIST+=("test/tools/schema_check_unit_test.dart")
          [[ -f "test/tools/migrate_output_variants_test.dart" ]] && WHITELIST+=("test/tools/migrate_output_variants_test.dart")

          if [[ ${#WHITELIST[@]} -eq 0 ]]; then
            echo "has_tests=0" >> "$GITHUB_OUTPUT"
          else
            printf '%s\n' "${WHITELIST[@]}" | tee whitelist.txt
            echo "has_tests=1" >> "$GITHUB_OUTPUT"
            echo "list=$(tr '\n' ' ' < whitelist.txt)" >> "$GITHUB_OUTPUT"
          fi

      - name: Run tests (Dart, compact)
        if: steps.files.outputs.has_tests == '1'
        shell: bash
        run: |
          dart test -r compact ${{ steps.files.outputs.list }}

      - name: No whitelist tests found
        if: steps.files.outputs.has_tests != '1'
        run: echo "No whitelisted tests found. Skipping."
