name: Unit Tests (compact, non-blocking)

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    continue-on-error: true  # non-blocking
    steps:
      - uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - name: Run unit tests (lib/test only)
        run: |
          dart test -r expanded test
