name: Unit Tests

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

concurrency:
  group: unit-tests-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect changes (docs vs code)
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            docs:
              - '**/*.md'
              - 'docs/**'
              - '**/*.mdx'
              - '**/*.rst'
            code:
              - '!**/*.md'
              - '!docs/**'
              - '!**/*.mdx'
              - '!**/*.rst'
              - '**/*'

      - name: Compute doc-only flag
        id: compute
        run: |
          if [ "${{ steps.changes.outputs.docs }}" = "true" ] && [ "${{ steps.changes.outputs.code }}" != "true" ]; then
            echo "doc_only=true" >> $GITHUB_OUTPUT
          else
            echo "doc_only=false" >> $GITHUB_OUTPUT
          fi

      # ---------- FAST-PATH (doc-only PR) ----------
      - name: Fast-path mock run (doc-only PR)
        if: ${{ steps.compute.outputs.doc_only == 'true' }}
        run: |
          echo "Doc-only PR detected — skipping heavy build/tests."
          echo "Unit Tests (fast-path) passed ✅"

      # ---------- FULL TESTS (code PR) ----------
      - name: Set up Flutter
        if: ${{ steps.compute.outputs.doc_only != 'true' }}
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Flutter version
        if: ${{ steps.compute.outputs.doc_only != 'true' }}
        run: flutter --version

      - name: Cache Pub dependencies
        if: ${{ steps.compute.outputs.doc_only != 'true' }}
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Install deps
        if: ${{ steps.compute.outputs.doc_only != 'true' }}
        run: flutter pub get

      - name: Run unit tests (parallel)
        if: ${{ steps.compute.outputs.doc_only != 'true' }}
        run: flutter test --coverage --concurrency=6
