name: Unit Tests

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

concurrency:
  group: unit-tests-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Robust fast-path: doc/CI-only check via git diff (без --depth)
      - name: Compute fast-path (doc/CI-only)
        id: compute
        shell: bash
        run: |
          set -euo pipefail
          BASE="${{ github.base_ref }}"
          if [ -z "$BASE" ]; then BASE="main"; fi
          echo "base_ref=$BASE"

          # подтянуть base-ветку целиком (без --depth)
          git fetch --no-tags origin "$BASE:refs/remotes/origin/$BASE" >/dev/null 2>&1 || true

          CHANGED=$(git diff --name-only "origin/$BASE"...HEAD || git diff --name-only "origin/$BASE")
          echo "changed_files=$CHANGED"

          FAST=true
          for f in $CHANGED; do
            if [[ "$f" =~ \.md$ || "$f" =~ \.mdx$ || "$f" =~ \.rst$ || "$f" == docs/* || "$f" == .github/workflows/* ]]; then
              : # ok — docs/CI
            else
              FAST=false; break
            fi
          done

          echo "fast_path=$FAST" | tee -a "$GITHUB_OUTPUT"

      # ---------- FAST-PATH (docs/CI-only) ----------
      - name: Fast-path mock run
        if: ${{ steps.compute.outputs.fast_path == 'true' }}
        run: |
          echo "Docs/CI-only PR detected — skipping heavy build/tests."
          echo "Unit Tests (fast-path) passed ✅"

      # ---------- FULL TESTS (code PR) ----------
      - name: Set up Flutter
        if: ${{ steps.compute.outputs.fast_path != 'true' }}
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Flutter version
        if: ${{ steps.compute.outputs.fast_path != 'true' }}
        run: flutter --version

      - name: Cache Pub dependencies
        if: ${{ steps.compute.outputs.fast_path != 'true' }}
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Install deps
        if: ${{ steps.compute.outputs.fast_path != 'true' }}
        run: flutter pub get

      - name: Run unit tests (parallel)
        if: ${{ steps.compute.outputs.fast_path != 'true' }}
        run: flutter test --coverage --concurrency=6
