name: Unit tests

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - '**/*.md'

jobs:
  unit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Detect test dirs
        id: dirs
        shell: bash
        run: |
          set -euo pipefail
          DIRS=()
          [[ -d test ]] && DIRS+=("test")
          if [[ ${#DIRS[@]} -eq 0 ]]; then
            echo "has_tests=0" >> "$GITHUB_OUTPUT"
          else
            printf '%s ' "${DIRS[@]}" > dirs.txt
            echo "has_tests=1" >> "$GITHUB_OUTPUT"
            echo "list=$(cat dirs.txt)" >> "$GITHUB_OUTPUT"
          fi

      - name: Run tests (Flutter)
        if: steps.dirs.outputs.has_tests == '1'
        run: |
          # Flutter-тесты корректно выполняют и pure-Dart тесты
          flutter test -r expanded ${{ steps.dirs.outputs.list }}

      - name: No tests found
        if: steps.dirs.outputs.has_tests != '1'
        run: echo "No tests found. Skipping."
