name: Unit Tests

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

concurrency:
  group: unit-tests-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Classify changes: docs, CI, or code
      - name: Detect changes (docs / ci / code)
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            docs:
              - '**/*.md'
              - 'docs/**'
              - '**/*.mdx'
              - '**/*.rst'
            ci:
              - '.github/workflows/**'
            code:
              - '!**/*.md'
              - '!docs/**'
              - '!**/*.mdx'
              - '!**/*.rst'
              - '!.github/workflows/**'
              - '**/*.dart'
              - 'lib/**'
              - 'packages/**'
              - 'bin/**'
              - 'android/**'
              - 'ios/**'
              - 'macos/**'
              - 'linux/**'
              - 'windows/**'
              - 'web/**'

      - name: Compute fast-path flag
        id: compute
        run: |
          DOCS="${{ steps.changes.outputs.docs }}"
          CI="${{ steps.changes.outputs.ci }}"
          CODE="${{ steps.changes.outputs.code }}"
          if { [ "$DOCS" = "true" ] || [ "$CI" = "true" ]; } && [ "$CODE" != "true" ]; then
            echo "fast_path=true" >> $GITHUB_OUTPUT
          else
            echo "fast_path=false" >> $GITHUB_OUTPUT
          fi

      # ---------- FAST-PATH (docs/CI-only) ----------
      - name: Fast-path mock run
        if: ${{ steps.compute.outputs.fast_path == 'true' }}
        run: |
          echo "Docs/CI-only PR detected — skipping heavy build/tests."
          echo "Unit Tests (fast-path) passed ✅"

      # ---------- FULL TESTS (code PR) ----------
      - name: Set up Flutter
        if: ${{ steps.compute.outputs.fast_path != 'true' }}
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Flutter version
        if: ${{ steps.compute.outputs.fast_path != 'true' }}
        run: flutter --version

      - name: Cache Pub dependencies
        if: ${{ steps.compute.outputs.fast_path != 'true' }}
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Install deps
        if: ${{ steps.compute.outputs.fast_path != 'true' }}
        run: flutter pub get

      - name: Run unit tests (parallel)
        if: ${{ steps.compute.outputs.fast_path != 'true' }}
        run: flutter test --coverage --concurrency=6
