name: Unit Tests

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

concurrency:
  group: unit-tests-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Compute fast-path (docs/CI-only)
        id: compute
        shell: bash
        run: |
          set -euo pipefail
          BASE="${{ github.base_ref }}"
          if [ -z "$BASE" ]; then BASE="main"; fi
          git fetch --no-tags origin "$BASE:refs/remotes/origin/$BASE" >/dev/null 2>&1 || true

          CHANGED=$(git diff --name-only "origin/$BASE"...HEAD || git diff --name-only "origin/$BASE")
          echo "changed_files=$CHANGED"

          FAST=true
          for f in $CHANGED; do
            if [[ "$f" =~ \.md$ || "$f" =~ \.mdx$ || "$f" =~ \.rst$ || "$f" == docs/* || "$f" == .github/workflows/* ]]; then
              :
            else
              FAST=false; break
            fi
          done
          echo "fast_path=$FAST" | tee -a "$GITHUB_OUTPUT"

      - name: Fast-path mock run
        if: ${{ steps.compute.outputs.fast_path == 'true' }}
        run: |
          echo "Docs/CI-only PR detected — skipping heavy build/tests."
          echo "Unit Tests (fast-path) passed ✅"

      - name: Set up Flutter
        if: ${{ steps.compute.outputs.fast_path != 'true' }}
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Flutter version
        if: ${{ steps.compute.outputs.fast_path != 'true' }}
        run: flutter --version

      - name: Cache Pub dependencies
        if: ${{ steps.compute.outputs.fast_path != 'true' }}
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Install deps
        if: ${{ steps.compute.outputs.fast_path != 'true' }}
        run: flutter pub get

      - name: Run unit tests (fail if none found)
        if: ${{ steps.compute.outputs.fast_path != 'true' }}
        run: |
          set -e
          COUNT=$(find test -type f -name "*_test.dart" | wc -l)
          if [ "$COUNT" -eq 0 ]; then
            echo "❌ No *_test.dart files found under /test — failing."
            exit 1
          fi
          flutter test --coverage --concurrency=6

      - name: Upload coverage artifact
        if: ${{ steps.compute.outputs.fast_path != 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/lcov.info