name: Unit Tests (compact)

on:
  pull_request:
    branches: [main]
    paths:
      - 'lib/**'
      - 'test/**'
  push:
    branches: [main]
    paths:
      - 'lib/**'
      - 'test/**'

permissions:
  contents: read

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    continue-on-error: true   # не блокирует merge для codex/* и любых PR

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Get deps
        run: flutter pub get

      - name: Run unit tests (compact)
        run: |
          flutter test --no-pub --reporter=compact --concurrency=2
